image: node:6
services:
  - mongo
  - redis

stages:
  - test

test:
  stage: test
  before_script:
    - npm install
    - node test/fixtures/mongo-user.js test/fixtures/mongo-file.js
  script:
    - npm test
  tags:
    - docker
  variables:
    MONGO_URL: "mongodb://mongo:27017/hostr"
    REDIS_URL: "redis://redis:6379"
    DEBUG: "hostr*"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules
    - web/public/jspm_packages
