image: node:6
services:
  - postgres
  - redis

variables:
  POSTGRES_DB: hostr_test
  POSTGRES_USER: hostr_test
  POSTGRES_PASSWORD: ""

stages:
  - test

test:
  stage: test
  before_script:
    - npm install
    - npm run init
  script:
    - npm test
  tags:
    - docker
  variables:
    DATABASE_URL: "postgres://hostr_test@postgres:5432/hostr_test"
    REDIS_URL: "redis://redis:6379"
    DEBUG: "hostr*"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules
