image: node:6
services:
  - mongo

stages:
  - test

test:
  stage: test
  before_script:
    - npm install
    - jspm install
    - node test/fixtures/mongo-user.js test/fixtures/mongo-file.js
  script:
    - npm test
  tags:
    - docker

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules
    - web/public/jspm_packages
