image: node:6
services:
  - mongo
  - redis

stages:
  - test

test:
  stage: test
  before_script:
    - npm install
    - npm run init
  script:
    - npm test
  tags:
    - docker
  variables:
    MONGO_URL: "mongodb://mongo:27017/hostr"
    REDIS_URL: "redis://redis:6379"
    DEBUG: "hostr*"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules
