version: "2"

services:
  app:
    build: ./
    environment:
      DEBUG:
      NODE_ENV:
      WEB_BASE_URL:
      API_BASE_URL:
      UPLOAD_STORAGE_PATH:
      COOKIE_KEY:
      EMAIL_FROM:
      EMAIL_NAME:
      STATSD_HOST:
      DATABASE_URL:
      REDIS_URL:
      SENDGRID_KEY:
      VIRUSTOTAL_KEY:
    volumes:
      - ./:/app:z
      - uploads:/hostr/uploads
    ports:
      - "3000:3000"
    command: yarn run watch-server
  database:
    image: "postgres:18-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "hostr"
      POSTGRES_USER: "hostr"
      POSTGRES_DB: "hostr"
  redis:
    image: "redis:8-alpine"
    ports:
      - "6379:6379"

volumes:
  uploads:
