version: "2"

services:
  app:
    build: ./
    environment:
      DEBUG:
      NODE_ENV:
      WEB_BASE_URL:
      API_BASE_URL:
      UPLOAD_STORAGE_PATH:
      COOKIE_KEY:
      EMAIL_FROM:
      EMAIL_NAME:
      STATSD_HOST:
      DATABASE_URL:
      REDIS_URL:
      SENDGRID_KEY:
      STRIPE_SECRET_KEY:
      STRIPE_PUBLIC_KEY:
      AWS_ENDPOINT:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_BUCKET:
      VIRUSTOTAL_KEY:
      SENTRY_DSN:
    volumes:
      - ./:/app:z
      - uploads:/hostr/uploads
      - export:/export
    ports:
      - "3000:3000"
    command: yarn run watch-server
  worker:
    build: ./
    environment:
      DEBUG:
      NODE_ENV:
      WEB_BASE_URL:
      API_BASE_URL:
      UPLOAD_STORAGE_PATH:
      COOKIE_KEY:
      EMAIL_FROM:
      EMAIL_NAME:
      STATSD_HOST:
      DATABASE_URL:
      REDIS_URL:
      SENDGRID_KEY:
      STRIPE_SECRET_KEY:
      STRIPE_PUBLIC_KEY:
      AWS_ENDPOINT:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_BUCKET:
      VIRUSTOTAL_KEY:
      SENTRY_DSN:
    volumes:
      - ./:/app
      - uploads:/hostr/uploads
    ports:
      - "3001:3000"
    command: yarn run worker
  database:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "hostr"
      POSTGRES_USER: "hostr"
      POSTGRES_DB: "hostr"
  redis:
    image: "redis:8-alpine"
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    volumes:
      - export:/export
    command: server /export
    environment:
      MINIO_ACCESS_KEY: 7HYV3KPRGQ8Z5YCDNWC6
      MINIO_SECRET_KEY: "0kWP/ZkgIwQzgL9t4SGv9Uc93rO//OdyqMH329b/"

volumes:
  uploads:
  export:
