allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
overrides:
  yaml: ^2.8.3
  ansi-regex: ^6.0.0
  minimatch: ^10.0.0
  serialize-javascript: ^7.0.5
  debug: ^4.4.3
  qs: ^6.14.2
